project:
  type: book

book:
  title: "QuantitativeMethoden der Informatik"
  author: "Norman Markgraf"
  date: "7/01/2023"
  chapters:
    - index.qmd
    - Kapitel-1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    grid:
      margin-width: 350px
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png      
    
reference-location: margin
citation-location: margin
editor: visual

