project:
  type: book

book:
  title: "Quantitative Methoden der Informatik"
  author: "Norman Markgraf"
  date: "7/01/2023"
  chapters:
    - index.qmd
    - Kapitel-1.qmd
    - Kapitel-2.qmd
    - Kapitel-3.qmd
    - Kapitel-4.qmd
    - Kapitel-5.qmd
    - Kapitel-6.qmd
    - Kapitel-7.qmd
    - Kapitel-8.qmd
    - Kapitel-9.qmd
    - summary.qmd
    - references.qmd

lang: de

bibliography: references.bib

format:
  html:
    html-math-method: katex
    grid:
      margin-width: 350px
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png      
    
reference-location: margin
citation-location: margin
editor: visual
#crossref:
#  fig-prefix: Abbildung   # (default is "Figure")
